version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paymentdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - payment-net

  auth:
    build:
      context: ./auth-service
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=paymentdb
      - DB_USER=postgres
      - DB_PASS=password
      - KAFKA_BROKER=kafka:9092
    ports:
      - "5000:5000"
    depends_on:
      - db
      - kafka
    networks:
      - payment-net

  payment:
    build:
      context: ./payment-service
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=paymentdb
      - DB_USER=postgres
      - DB_PASS=password
      - KAFKA_BROKER=kafka:9092
    ports:
      - "5001:5001"
    depends_on:
      - db
      - kafka
    networks:
      - payment-net

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - payment-net
    depends_on:
      - auth
      - payment

  monitoring:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - payment-net

zookeeper:
  image: confluentinc/cp-zookeeper:latest
  ports:
    - 2181:2181
  environment:
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - payment-net

networks:
  payment-net:

volumes:
  db_data:
