version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paymentdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - payment-net

networks:
  payment-net:
    external: true

volumes:
  db_data:
