version: '3.8'

services:
  auth:
    build:
      context: ./auth-service
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=paymentdb
      - DB_USER=postgres
      - DB_PASS=password
      - KAFKA_BROKER=kafka:9092
    ports:
      - "5000:5000"
    depends_on:
      - db
      - kafka
    networks:
      - payment-net

networks:
  payment-net:
    external: true
