version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - payment-net
    depends_on:
      - auth
      - payment

networks:
  payment-net:
    external: true
